/*
 * Copyright 2026 The KmpRemoteCompose Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tneff.kmpremotecompose.remote.player.core

/**
 * REM-68 (Phase 2, dev-1) — the platform system-accent / Material-You palette: maps a `.rc` document's
 * theme color NAME (e.g. `color.system_accent1_100`, exactly the `NamedVariable` name, prefix included)
 * to an ARGB value. The host wires this into the player via the core name-override API (dev-2's
 * `NamedVariable` registry + `setNamedColorOverride`/precedence), so a `colorId` that carries a name
 * resolves to the real theme color instead of the doc's debug-placeholder `ColorConstant` fallback
 * (e.g. `color.system_accent1_100` → `#D9E2FF`, NOT the `#00FF00` debug fallback). See REM-61/REM-67.
 *
 * - **Android** ([androidMain]): API 31+ reads the **real device** Material-You colors
 *   (`Resources.getSystem().getColor(android.R.color.system_*)` via `getIdentifier`); pre-31 falls back
 *   to [BASELINE_SYSTEM_PALETTE]. No Android `Color`/`Density` leaks into `commonMain` (PROJECT_CONTEXT §5).
 * - **iOS** ([iosMain]): no system accent → **mirrors the Android Material-You baseline**
 *   ([BASELINE_SYSTEM_PALETTE]) for cross-platform parity (PO decision).
 *
 * [BASELINE_SYSTEM_PALETTE] values are the **day/light** tones extracted from the Android framework
 * baseline (`framework-res` `system_*_light`), so a static capture is deterministic. A doc that names a
 * base tone (`color.system_accent1_500`) gets its light value; an explicit `…_light`/`…_dark` name gets
 * that exact value.
 */
expect fun systemAccentPalette(): Map<String, Int>

/**
 * The static Material-You **baseline** (day/light) palette, name (with `color.` prefix) → ARGB. Source:
 * Android `framework-res` baseline `system_*` resources (light variants). Used verbatim on iOS and as
 * the Android pre-31 fallback. Generated from the framework baseline — do not hand-edit values.
 */
internal val BASELINE_SYSTEM_PALETTE: Map<String, Int> = mapOf(
        "color.system_accent1_0" to 0xFFFFFFFF.toInt(),
        "color.system_accent1_0_dark" to 0xFFFFFFFF.toInt(),
        "color.system_accent1_0_light" to 0xFFFFFFFF.toInt(),
        "color.system_accent1_10" to 0xFFFEFBFF.toInt(),
        "color.system_accent1_100" to 0xFFD9E2FF.toInt(),
        "color.system_accent1_1000" to 0xFF000000.toInt(),
        "color.system_accent1_1000_dark" to 0xFF000000.toInt(),
        "color.system_accent1_1000_light" to 0xFF000000.toInt(),
        "color.system_accent1_100_dark" to 0xFFD9E2FF.toInt(),
        "color.system_accent1_100_light" to 0xFFD9E2FF.toInt(),
        "color.system_accent1_10_dark" to 0xFFFEFBFF.toInt(),
        "color.system_accent1_10_light" to 0xFFFEFBFF.toInt(),
        "color.system_accent1_200" to 0xFFB3C6F9.toInt(),
        "color.system_accent1_200_dark" to 0xFFB8C6EE.toInt(),
        "color.system_accent1_200_light" to 0xFFB3C6F9.toInt(),
        "color.system_accent1_300" to 0xFF98AADC.toInt(),
        "color.system_accent1_300_dark" to 0xFF9DABD1.toInt(),
        "color.system_accent1_300_light" to 0xFF98AADC.toInt(),
        "color.system_accent1_400" to 0xFF7E90C0.toInt(),
        "color.system_accent1_400_dark" to 0xFF8390B6.toInt(),
        "color.system_accent1_400_light" to 0xFF7E90C0.toInt(),
        "color.system_accent1_50" to 0xFFEEF0FF.toInt(),
        "color.system_accent1_500" to 0xFF6476A5.toInt(),
        "color.system_accent1_500_dark" to 0xFF69769B.toInt(),
        "color.system_accent1_500_light" to 0xFF6476A5.toInt(),
        "color.system_accent1_50_dark" to 0xFFEEF0FF.toInt(),
        "color.system_accent1_50_light" to 0xFFEEF0FF.toInt(),
        "color.system_accent1_600" to 0xFF4B5D8B.toInt(),
        "color.system_accent1_600_dark" to 0xFF505E81.toInt(),
        "color.system_accent1_600_light" to 0xFF4B5D8B.toInt(),
        "color.system_accent1_700" to 0xFF334671.toInt(),
        "color.system_accent1_700_dark" to 0xFF394668.toInt(),
        "color.system_accent1_700_light" to 0xFF334671.toInt(),
        "color.system_accent1_800" to 0xFF1B2F59.toInt(),
        "color.system_accent1_800_dark" to 0xFF223050.toInt(),
        "color.system_accent1_800_light" to 0xFF1B2F59.toInt(),
        "color.system_accent1_900" to 0xFF021943.toInt(),
        "color.system_accent1_900_dark" to 0xFF0B1A3A.toInt(),
        "color.system_accent1_900_light" to 0xFF021943.toInt(),
        "color.system_accent2_0" to 0xFFFFFFFF.toInt(),
        "color.system_accent2_0_dark" to 0xFFFFFFFF.toInt(),
        "color.system_accent2_0_light" to 0xFFFFFFFF.toInt(),
        "color.system_accent2_10" to 0xFFFEFBFF.toInt(),
        "color.system_accent2_100" to 0xFFDCE2F9.toInt(),
        "color.system_accent2_1000" to 0xFF000000.toInt(),
        "color.system_accent2_1000_dark" to 0xFF000000.toInt(),
        "color.system_accent2_1000_light" to 0xFF000000.toInt(),
        "color.system_accent2_100_dark" to 0xFFDCE2F9.toInt(),
        "color.system_accent2_100_light" to 0xFFDCE2F9.toInt(),
        "color.system_accent2_10_dark" to 0xFFFEFBFF.toInt(),
        "color.system_accent2_10_light" to 0xFFFEFBFF.toInt(),
        "color.system_accent2_200" to 0xFFC0C6DC.toInt(),
        "color.system_accent2_200_dark" to 0xFFC0C6DC.toInt(),
        "color.system_accent2_200_light" to 0xFFC0C6DC.toInt(),
        "color.system_accent2_300" to 0xFFA4ABC1.toInt(),
        "color.system_accent2_300_dark" to 0xFFA4ABC1.toInt(),
        "color.system_accent2_300_light" to 0xFFA4ABC1.toInt(),
        "color.system_accent2_400" to 0xFF8A90A5.toInt(),
        "color.system_accent2_400_dark" to 0xFF8A90A5.toInt(),
        "color.system_accent2_400_light" to 0xFF8A90A5.toInt(),
        "color.system_accent2_50" to 0xFFEEF0FF.toInt(),
        "color.system_accent2_500" to 0xFF70778B.toInt(),
        "color.system_accent2_500_dark" to 0xFF70778B.toInt(),
        "color.system_accent2_500_light" to 0xFF70778B.toInt(),
        "color.system_accent2_50_dark" to 0xFFEEF0FF.toInt(),
        "color.system_accent2_50_light" to 0xFFEEF0FF.toInt(),
        "color.system_accent2_600" to 0xFF575E71.toInt(),
        "color.system_accent2_600_dark" to 0xFF575E71.toInt(),
        "color.system_accent2_600_light" to 0xFF575E71.toInt(),
        "color.system_accent2_700" to 0xFF404659.toInt(),
        "color.system_accent2_700_dark" to 0xFF404659.toInt(),
        "color.system_accent2_700_light" to 0xFF404659.toInt(),
        "color.system_accent2_800" to 0xFF2A3042.toInt(),
        "color.system_accent2_800_dark" to 0xFF2A3042.toInt(),
        "color.system_accent2_800_light" to 0xFF2A3042.toInt(),
        "color.system_accent2_900" to 0xFF151B2C.toInt(),
        "color.system_accent2_900_dark" to 0xFF151B2C.toInt(),
        "color.system_accent2_900_light" to 0xFF151B2C.toInt(),
        "color.system_accent3_0" to 0xFFFFFFFF.toInt(),
        "color.system_accent3_0_dark" to 0xFFFFFFFF.toInt(),
        "color.system_accent3_0_light" to 0xFFFFFFFF.toInt(),
        "color.system_accent3_10" to 0xFFFFFBFF.toInt(),
        "color.system_accent3_100" to 0xFFEFDBFF.toInt(),
        "color.system_accent3_1000" to 0xFF000000.toInt(),
        "color.system_accent3_1000_dark" to 0xFF000000.toInt(),
        "color.system_accent3_1000_light" to 0xFF000000.toInt(),
        "color.system_accent3_100_dark" to 0xFFEFDBFF.toInt(),
        "color.system_accent3_100_light" to 0xFFEFDBFF.toInt(),
        "color.system_accent3_10_dark" to 0xFFFFFBFF.toInt(),
        "color.system_accent3_10_light" to 0xFFFFFBFF.toInt(),
        "color.system_accent3_200" to 0xFFD5BDEC.toInt(),
        "color.system_accent3_200_dark" to 0xFFD5BDEC.toInt(),
        "color.system_accent3_200_light" to 0xFFD5BDEC.toInt(),
        "color.system_accent3_300" to 0xFFB9A2D0.toInt(),
        "color.system_accent3_300_dark" to 0xFFB9A2D0.toInt(),
        "color.system_accent3_300_light" to 0xFFB9A2D0.toInt(),
        "color.system_accent3_400" to 0xFF9E88B4.toInt(),
        "color.system_accent3_400_dark" to 0xFF9E88B4.toInt(),
        "color.system_accent3_400_light" to 0xFF9E88B4.toInt(),
        "color.system_accent3_50" to 0xFFF9ECFF.toInt(),
        "color.system_accent3_500" to 0xFF836E99.toInt(),
        "color.system_accent3_500_dark" to 0xFF836E99.toInt(),
        "color.system_accent3_500_light" to 0xFF836E99.toInt(),
        "color.system_accent3_50_dark" to 0xFFF9ECFF.toInt(),
        "color.system_accent3_50_light" to 0xFFF9ECFF.toInt(),
        "color.system_accent3_600" to 0xFF6A567F.toInt(),
        "color.system_accent3_600_dark" to 0xFF6A567F.toInt(),
        "color.system_accent3_600_light" to 0xFF6A567F.toInt(),
        "color.system_accent3_700" to 0xFF513F66.toInt(),
        "color.system_accent3_700_dark" to 0xFF513F66.toInt(),
        "color.system_accent3_700_light" to 0xFF513F66.toInt(),
        "color.system_accent3_800" to 0xFF3A284E.toInt(),
        "color.system_accent3_800_dark" to 0xFF3A284E.toInt(),
        "color.system_accent3_800_light" to 0xFF3A284E.toInt(),
        "color.system_accent3_900" to 0xFF241338.toInt(),
        "color.system_accent3_900_dark" to 0xFF241338.toInt(),
        "color.system_accent3_900_light" to 0xFF241338.toInt(),
        "color.system_background_dark" to 0xFF0D0E12.toInt(),
        "color.system_background_light" to 0xFFFAF8FE.toInt(),
        "color.system_control_activated_dark" to 0xFF445274.toInt(),
        "color.system_control_activated_light" to 0xFFB9CBFF.toInt(),
        "color.system_control_highlight_dark" to 0xFFFFFFFF.toInt(),
        "color.system_control_highlight_light" to 0xFF000000.toInt(),
        "color.system_control_normal_dark" to 0xFFA9AAB5.toInt(),
        "color.system_control_normal_light" to 0xFF5D5F68.toInt(),
        "color.system_error_0" to 0xFFFFFFFF.toInt(),
        "color.system_error_0_dark" to 0xFFFFFFFF.toInt(),
        "color.system_error_0_light" to 0xFFFFFFFF.toInt(),
        "color.system_error_10" to 0xFFFFFBFF.toInt(),
        "color.system_error_100" to 0xFFFFDAD7.toInt(),
        "color.system_error_1000" to 0xFF000000.toInt(),
        "color.system_error_1000_dark" to 0xFF000000.toInt(),
        "color.system_error_1000_light" to 0xFF000000.toInt(),
        "color.system_error_100_dark" to 0xFFFFDAD7.toInt(),
        "color.system_error_100_light" to 0xFFFFDAD7.toInt(),
        "color.system_error_10_dark" to 0xFFFFFBFF.toInt(),
        "color.system_error_10_light" to 0xFFFFFBFF.toInt(),
        "color.system_error_200" to 0xFFFFB3AE.toInt(),
        "color.system_error_200_dark" to 0xFFFFB3AE.toInt(),
        "color.system_error_200_light" to 0xFFFFB3AE.toInt(),
        "color.system_error_300" to 0xFFFF8983.toInt(),
        "color.system_error_300_dark" to 0xFFFF8983.toInt(),
        "color.system_error_300_light" to 0xFFFF8983.toInt(),
        "color.system_error_400" to 0xFFE96863.toInt(),
        "color.system_error_400_dark" to 0xFFE96863.toInt(),
        "color.system_error_400_light" to 0xFFE96863.toInt(),
        "color.system_error_50" to 0xFFFFEDEB.toInt(),
        "color.system_error_500" to 0xFFC84F4C.toInt(),
        "color.system_error_500_dark" to 0xFFC84F4C.toInt(),
        "color.system_error_500_light" to 0xFFC84F4C.toInt(),
        "color.system_error_50_dark" to 0xFFFFEDEB.toInt(),
        "color.system_error_50_light" to 0xFFFFEDEB.toInt(),
        "color.system_error_600" to 0xFFA73736.toInt(),
        "color.system_error_600_dark" to 0xFFA73736.toInt(),
        "color.system_error_600_light" to 0xFFA73736.toInt(),
        "color.system_error_700" to 0xFF871F21.toInt(),
        "color.system_error_700_dark" to 0xFF871F21.toInt(),
        "color.system_error_700_light" to 0xFF871F21.toInt(),
        "color.system_error_800" to 0xFF67040D.toInt(),
        "color.system_error_800_dark" to 0xFF67040D.toInt(),
        "color.system_error_800_light" to 0xFF67040D.toInt(),
        "color.system_error_900" to 0xFF410004.toInt(),
        "color.system_error_900_dark" to 0xFF410004.toInt(),
        "color.system_error_900_light" to 0xFF410004.toInt(),
        "color.system_error_container_dark" to 0xFF871F21.toInt(),
        "color.system_error_container_light" to 0xFFFA746F.toInt(),
        "color.system_error_dark" to 0xFFFA746F.toInt(),
        "color.system_error_dim_dark" to 0xFFC54D4A.toInt(),
        "color.system_error_dim_light" to 0xFF67040D.toInt(),
        "color.system_error_light" to 0xFFA83836.toInt(),
        "color.system_neutral1_0" to 0xFFFFFFFF.toInt(),
        "color.system_neutral1_0_dark" to 0xFFFFFFFF.toInt(),
        "color.system_neutral1_0_light" to 0xFFFFFFFF.toInt(),
        "color.system_neutral1_10" to 0xFFFEFBFF.toInt(),
        "color.system_neutral1_100" to 0xFFE3E2E7.toInt(),
        "color.system_neutral1_1000" to 0xFF000000.toInt(),
        "color.system_neutral1_1000_dark" to 0xFF000000.toInt(),
        "color.system_neutral1_1000_light" to 0xFF000000.toInt(),
        "color.system_neutral1_100_dark" to 0xFFE3E2E7.toInt(),
        "color.system_neutral1_100_light" to 0xFFE3E2E7.toInt(),
        "color.system_neutral1_10_dark" to 0xFFFEFBFF.toInt(),
        "color.system_neutral1_10_light" to 0xFFFEFBFF.toInt(),
        "color.system_neutral1_200" to 0xFFC7C6CB.toInt(),
        "color.system_neutral1_200_dark" to 0xFFC7C6CB.toInt(),
        "color.system_neutral1_200_light" to 0xFFC7C6CB.toInt(),
        "color.system_neutral1_300" to 0xFFABABB0.toInt(),
        "color.system_neutral1_300_dark" to 0xFFABABB0.toInt(),
        "color.system_neutral1_300_light" to 0xFFABABB0.toInt(),
        "color.system_neutral1_400" to 0xFF909095.toInt(),
        "color.system_neutral1_400_dark" to 0xFF909095.toInt(),
        "color.system_neutral1_400_light" to 0xFF909095.toInt(),
        "color.system_neutral1_50" to 0xFFF1F0F6.toInt(),
        "color.system_neutral1_500" to 0xFF76777C.toInt(),
        "color.system_neutral1_500_dark" to 0xFF76777C.toInt(),
        "color.system_neutral1_500_light" to 0xFF76777C.toInt(),
        "color.system_neutral1_50_dark" to 0xFFF1F0F6.toInt(),
        "color.system_neutral1_50_light" to 0xFFF1F0F6.toInt(),
        "color.system_neutral1_600" to 0xFF5E5E63.toInt(),
        "color.system_neutral1_600_dark" to 0xFF5E5E63.toInt(),
        "color.system_neutral1_600_light" to 0xFF5E5E63.toInt(),
        "color.system_neutral1_700" to 0xFF46464B.toInt(),
        "color.system_neutral1_700_dark" to 0xFF46464B.toInt(),
        "color.system_neutral1_700_light" to 0xFF46464B.toInt(),
        "color.system_neutral1_800" to 0xFF2F3035.toInt(),
        "color.system_neutral1_800_dark" to 0xFF2F3035.toInt(),
        "color.system_neutral1_800_light" to 0xFF2F3035.toInt(),
        "color.system_neutral1_900" to 0xFF1A1B20.toInt(),
        "color.system_neutral1_900_dark" to 0xFF1A1B20.toInt(),
        "color.system_neutral1_900_light" to 0xFF1A1B20.toInt(),
        "color.system_neutral2_0" to 0xFFFFFFFF.toInt(),
        "color.system_neutral2_0_dark" to 0xFFFFFFFF.toInt(),
        "color.system_neutral2_0_light" to 0xFFFFFFFF.toInt(),
        "color.system_neutral2_10" to 0xFFFEFBFF.toInt(),
        "color.system_neutral2_100" to 0xFFE1E2ED.toInt(),
        "color.system_neutral2_1000" to 0xFF000000.toInt(),
        "color.system_neutral2_1000_dark" to 0xFF000000.toInt(),
        "color.system_neutral2_1000_light" to 0xFF000000.toInt(),
        "color.system_neutral2_100_dark" to 0xFFE1E2ED.toInt(),
        "color.system_neutral2_100_light" to 0xFFE1E2ED.toInt(),
        "color.system_neutral2_10_dark" to 0xFFFEFBFF.toInt(),
        "color.system_neutral2_10_light" to 0xFFFEFBFF.toInt(),
        "color.system_neutral2_200" to 0xFFC5C6D0.toInt(),
        "color.system_neutral2_200_dark" to 0xFFC5C6D0.toInt(),
        "color.system_neutral2_200_light" to 0xFFC5C6D0.toInt(),
        "color.system_neutral2_300" to 0xFFA9ABB5.toInt(),
        "color.system_neutral2_300_dark" to 0xFFA9ABB5.toInt(),
        "color.system_neutral2_300_light" to 0xFFA9ABB5.toInt(),
        "color.system_neutral2_400" to 0xFF8E909A.toInt(),
        "color.system_neutral2_400_dark" to 0xFF8E909A.toInt(),
        "color.system_neutral2_400_light" to 0xFF8E909A.toInt(),
        "color.system_neutral2_50" to 0xFFEFF0FB.toInt(),
        "color.system_neutral2_500" to 0xFF757780.toInt(),
        "color.system_neutral2_500_dark" to 0xFF757780.toInt(),
        "color.system_neutral2_500_light" to 0xFF757780.toInt(),
        "color.system_neutral2_50_dark" to 0xFFEFF0FB.toInt(),
        "color.system_neutral2_50_light" to 0xFFEFF0FB.toInt(),
        "color.system_neutral2_600" to 0xFF5C5E67.toInt(),
        "color.system_neutral2_600_dark" to 0xFF5C5E67.toInt(),
        "color.system_neutral2_600_light" to 0xFF5C5E67.toInt(),
        "color.system_neutral2_700" to 0xFF44464F.toInt(),
        "color.system_neutral2_700_dark" to 0xFF44464F.toInt(),
        "color.system_neutral2_700_light" to 0xFF44464F.toInt(),
        "color.system_neutral2_800" to 0xFF2E3038.toInt(),
        "color.system_neutral2_800_dark" to 0xFF2E3038.toInt(),
        "color.system_neutral2_800_light" to 0xFF2E3038.toInt(),
        "color.system_neutral2_900" to 0xFF191B23.toInt(),
        "color.system_neutral2_900_dark" to 0xFF191B23.toInt(),
        "color.system_neutral2_900_light" to 0xFF191B23.toInt(),
        "color.system_on_background_dark" to 0xFFE4E5F0.toInt(),
        "color.system_on_background_light" to 0xFF30323A.toInt(),
        "color.system_on_error_container_dark" to 0xFFFF9993.toInt(),
        "color.system_on_error_container_light" to 0xFF6E0A12.toInt(),
        "color.system_on_error_dark" to 0xFF490006.toInt(),
        "color.system_on_error_light" to 0xFFFFF7F6.toInt(),
        "color.system_on_primary_container_dark" to 0xFFDAE3FF.toInt(),
        "color.system_on_primary_container_light" to 0xFF30436E.toInt(),
        "color.system_on_primary_dark" to 0xFF323F60.toInt(),
        "color.system_on_primary_fixed" to 0xFF1B2F59.toInt(),
        "color.system_on_primary_fixed_dark" to 0xFF243152.toInt(),
        "color.system_on_primary_fixed_light" to 0xFF1B2F59.toInt(),
        "color.system_on_primary_fixed_variant" to 0xFF394C78.toInt(),
        "color.system_on_primary_fixed_variant_dark" to 0xFF414E70.toInt(),
        "color.system_on_primary_fixed_variant_light" to 0xFF394C78.toInt(),
        "color.system_on_primary_light" to 0xFFF9F8FF.toInt(),
        "color.system_on_secondary_container_dark" to 0xFFB8BFD5.toInt(),
        "color.system_on_secondary_container_light" to 0xFF4B5164.toInt(),
        "color.system_on_secondary_dark" to 0xFF394052.toInt(),
        "color.system_on_secondary_fixed" to 0xFF383F51.toInt(),
        "color.system_on_secondary_fixed_dark" to 0xFF383F51.toInt(),
        "color.system_on_secondary_fixed_light" to 0xFF383F51.toInt(),
        "color.system_on_secondary_fixed_variant" to 0xFF555B6E.toInt(),
        "color.system_on_secondary_fixed_variant_dark" to 0xFF555B6E.toInt(),
        "color.system_on_secondary_fixed_variant_light" to 0xFF555B6E.toInt(),
        "color.system_on_secondary_light" to 0xFFF9F8FF.toInt(),
        "color.system_on_shade_active_dark" to 0xFF0B1A3A.toInt(),
        "color.system_on_shade_active_light" to 0xFF516391.toInt(),
        "color.system_on_shade_active_variant_dark" to 0xFF394668.toInt(),
        "color.system_on_shade_active_variant_light" to 0xFF334671.toInt(),
        "color.system_on_shade_inactive_dark" to 0xFFA9ABB5.toInt(),
        "color.system_on_shade_inactive_light" to 0xFFE1E2ED.toInt(),
        "color.system_on_shade_inactive_variant_dark" to 0xFFC5C6D0.toInt(),
        "color.system_on_shade_inactive_variant_light" to 0xFFC5C6D0.toInt(),
        "color.system_on_surface_dark" to 0xFFE4E5F0.toInt(),
        "color.system_on_surface_light" to 0xFF30323A.toInt(),
        "color.system_on_surface_variant_dark" to 0xFFA9AAB5.toInt(),
        "color.system_on_surface_variant_light" to 0xFF5D5F68.toInt(),
        "color.system_on_tertiary_container_dark" to 0xFF523F67.toInt(),
        "color.system_on_tertiary_container_light" to 0xFF523F67.toInt(),
        "color.system_on_tertiary_dark" to 0xFF5B4870.toInt(),
        "color.system_on_tertiary_fixed" to 0xFF3E2C52.toInt(),
        "color.system_on_tertiary_fixed_dark" to 0xFF3E2C52.toInt(),
        "color.system_on_tertiary_fixed_light" to 0xFF3E2C52.toInt(),
        "color.system_on_tertiary_fixed_variant" to 0xFF5C4871.toInt(),
        "color.system_on_tertiary_fixed_variant_dark" to 0xFF5C4871.toInt(),
        "color.system_on_tertiary_fixed_variant_light" to 0xFF5C4871.toInt(),
        "color.system_on_tertiary_light" to 0xFFFFF6FF.toInt(),
        "color.system_on_theme_app_dark" to 0xFFB8C6EE.toInt(),
        "color.system_on_theme_app_light" to 0xFF263963.toInt(),
        "color.system_outline_dark" to 0xFF73757F.toInt(),
        "color.system_outline_light" to 0xFF787A84.toInt(),
        "color.system_outline_variant_dark" to 0xFF454850.toInt(),
        "color.system_outline_variant_light" to 0xFFB0B1BC.toInt(),
        "color.system_palette_key_color_error_dark" to 0xFFC84F4C.toInt(),
        "color.system_palette_key_color_error_light" to 0xFFC84F4C.toInt(),
        "color.system_palette_key_color_neutral_dark" to 0xFF77777C.toInt(),
        "color.system_palette_key_color_neutral_light" to 0xFF77777C.toInt(),
        "color.system_palette_key_color_neutral_variant_dark" to 0xFF757781.toInt(),
        "color.system_palette_key_color_neutral_variant_light" to 0xFF757781.toInt(),
        "color.system_palette_key_color_primary_dark" to 0xFF69769A.toInt(),
        "color.system_palette_key_color_primary_light" to 0xFF6476A5.toInt(),
        "color.system_palette_key_color_secondary_dark" to 0xFF70778B.toInt(),
        "color.system_palette_key_color_secondary_light" to 0xFF70778B.toInt(),
        "color.system_palette_key_color_tertiary_dark" to 0xFF836E99.toInt(),
        "color.system_palette_key_color_tertiary_light" to 0xFF836E99.toInt(),
        "color.system_primary_container_dark" to 0xFF445274.toInt(),
        "color.system_primary_container_light" to 0xFFB9CBFF.toInt(),
        "color.system_primary_dark" to 0xFFB8C6EE.toInt(),
        "color.system_primary_dim_dark" to 0xFFABB8E0.toInt(),
        "color.system_primary_dim_light" to 0xFF40527E.toInt(),
        "color.system_primary_fixed" to 0xFFB9CBFF.toInt(),
        "color.system_primary_fixed_dark" to 0xFFC1CEF7.toInt(),
        "color.system_primary_fixed_dim" to 0xFFABBDF0.toInt(),
        "color.system_primary_fixed_dim_dark" to 0xFFB3C0E8.toInt(),
        "color.system_primary_fixed_dim_light" to 0xFFABBDF0.toInt(),
        "color.system_primary_fixed_light" to 0xFFB9CBFF.toInt(),
        "color.system_primary_light" to 0xFF4C5E8B.toInt(),
        "color.system_secondary_container_dark" to 0xFF353B4D.toInt(),
        "color.system_secondary_container_light" to 0xFFDCE2F9.toInt(),
        "color.system_secondary_dark" to 0xFFC0C6DC.toInt(),
        "color.system_secondary_dim_dark" to 0xFFB2B8CE.toInt(),
        "color.system_secondary_dim_light" to 0xFF4C5366.toInt(),
        "color.system_secondary_fixed" to 0xFFDCE2F9.toInt(),
        "color.system_secondary_fixed_dark" to 0xFFDCE2F9.toInt(),
        "color.system_secondary_fixed_dim" to 0xFFCED4EB.toInt(),
        "color.system_secondary_fixed_dim_dark" to 0xFFCED4EB.toInt(),
        "color.system_secondary_fixed_dim_light" to 0xFFCED4EB.toInt(),
        "color.system_secondary_fixed_light" to 0xFFDCE2F9.toInt(),
        "color.system_secondary_light" to 0xFF585F72.toInt(),
        "color.system_surface_bright_dark" to 0xFF292C34.toInt(),
        "color.system_surface_bright_light" to 0xFFFAF8FE.toInt(),
        "color.system_surface_container_dark" to 0xFF17191F.toInt(),
        "color.system_surface_container_high_dark" to 0xFF1D1F26.toInt(),
        "color.system_surface_container_high_light" to 0xFFE7E7F1.toInt(),
        "color.system_surface_container_highest_dark" to 0xFF23262E.toInt(),
        "color.system_surface_container_highest_light" to 0xFFE1E2ED.toInt(),
        "color.system_surface_container_light" to 0xFFEDEDF6.toInt(),
        "color.system_surface_container_low_dark" to 0xFF121318.toInt(),
        "color.system_surface_container_low_light" to 0xFFF3F3FA.toInt(),
        "color.system_surface_container_lowest_dark" to 0xFF000000.toInt(),
        "color.system_surface_container_lowest_light" to 0xFFFFFFFF.toInt(),
        "color.system_surface_dark" to 0xFF0D0E12.toInt(),
        "color.system_surface_dim_dark" to 0xFF0D0E12.toInt(),
        "color.system_surface_dim_light" to 0xFFD8D9E4.toInt(),
        "color.system_surface_effect_0_dark" to 0xFF223050.toInt(),
        "color.system_surface_effect_0_fallback_dark" to 0xFF2A3042.toInt(),
        "color.system_surface_effect_0_fallback_light" to 0xFFC0C6DC.toInt(),
        "color.system_surface_effect_0_light" to 0xFFD9E2FF.toInt(),
        "color.system_surface_effect_1_dark" to 0xFF121317.toInt(),
        "color.system_surface_effect_1_light" to 0xFFFAF8FE.toInt(),
        "color.system_surface_effect_2_dark" to 0xFFD9E2FF.toInt(),
        "color.system_surface_effect_2_light" to 0xFFFFFFFF.toInt(),
        "color.system_surface_effect_3_dark" to 0xFFD9E2FF.toInt(),
        "color.system_surface_effect_3_light" to 0xFF4B5D8B.toInt(),
        "color.system_surface_light" to 0xFFFAF8FE.toInt(),
        "color.system_surface_tint_dark" to 0xFFB8C6EE.toInt(),
        "color.system_surface_tint_light" to 0xFF4C5E8B.toInt(),
        "color.system_surface_variant_dark" to 0xFF23262E.toInt(),
        "color.system_surface_variant_light" to 0xFFE1E2ED.toInt(),
        "color.system_tertiary_container_dark" to 0xFFE1C8F8.toInt(),
        "color.system_tertiary_container_light" to 0xFFE1C8F8.toInt(),
        "color.system_tertiary_dark" to 0xFFEDD8FF.toInt(),
        "color.system_tertiary_dim_dark" to 0xFFE1C8F8.toInt(),
        "color.system_tertiary_dim_light" to 0xFF5E4B73.toInt(),
        "color.system_tertiary_fixed" to 0xFFE1C8F8.toInt(),
        "color.system_tertiary_fixed_dark" to 0xFFE1C8F8.toInt(),
        "color.system_tertiary_fixed_dim" to 0xFFD3BAEA.toInt(),
        "color.system_tertiary_fixed_dim_dark" to 0xFFD3BAEA.toInt(),
        "color.system_tertiary_fixed_dim_light" to 0xFFD3BAEA.toInt(),
        "color.system_tertiary_fixed_light" to 0xFFE1C8F8.toInt(),
        "color.system_tertiary_light" to 0xFF6B5780.toInt(),
        "color.system_text_hint_inverse_dark" to 0xFF1A1B20.toInt(),
        "color.system_text_hint_inverse_light" to 0xFFE3E2E7.toInt(),
        "color.system_text_primary_inverse_dark" to 0xFF545559.toInt(),
        "color.system_text_primary_inverse_disable_only_dark" to 0xFF1A1B20.toInt(),
        "color.system_text_primary_inverse_disable_only_light" to 0xFFE3E2E7.toInt(),
        "color.system_text_primary_inverse_light" to 0xFF9D9CA2.toInt(),
        "color.system_text_secondary_and_tertiary_inverse_dark" to 0xFF44464F.toInt(),
        "color.system_text_secondary_and_tertiary_inverse_disabled_dark" to 0xFF1A1B20.toInt(),
        "color.system_text_secondary_and_tertiary_inverse_disabled_light" to 0xFFE3E2E7.toInt(),
        "color.system_text_secondary_and_tertiary_inverse_light" to 0xFFC5C6D0.toInt(),    )

/**
 * Best-effort aliases for the legacy framework theme-attr names (`android.*`) that a few docs reference,
 * mapped to the closest `color.system_*` baseline entry. **Approximation** — exact `android.R.attr.*`
 * theme resolution needs a themed `Context` and is deferred to Phase-2b; flagged so it is not mistaken
 * for an exact value. Resolved against the live palette so they track the real device colors on Android.
 */
internal val ANDROID_LEGACY_ALIASES: Map<String, String> = mapOf(
    "android.colorAccent" to "color.system_accent1_500",
    "android.colorPrimary" to "color.system_accent1_600",
    "android.colorPrimaryDark" to "color.system_accent1_700",
    "android.colorBackground" to "color.system_background_light",
    "android.colorButtonNormal" to "color.system_accent2_100",
    "android.colorControlActivated" to "color.system_accent1_500",
    "android.colorControlNormal" to "color.system_on_surface_variant_light",
    "android.colorError" to "color.system_error_light",
    "android.textColor" to "color.system_on_surface_light",
)

/**
 * REM-133: static legacy framework colors (`android.R.color.*`) that a few docs reference by their
 * `color.<name>` form. Unlike [ANDROID_LEGACY_ALIASES] these are NOT Material-You palette tones — they
 * are fixed public-framework constants (the canonical AOSP Holo day-tones from
 * `frameworks/base/core/res/res/values/colors.xml`), so they carry their own ARGB rather than mapping to
 * a `system_*` entry. Target-independent (same on every platform), which is why they live in the shared
 * [withLegacyAliases] merge. Resolves `color_table`'s previously-unmapped swatches that otherwise fell
 * back to the doc's green/cyan debug `ColorConstant`.
 */
internal val ANDROID_LEGACY_FIXED_COLORS: Map<String, Int> = mapOf(
    "color.holo_blue_bright" to 0xFF00DDFF.toInt(),
    "color.holo_blue_light" to 0xFF33B5E5.toInt(),
    "color.holo_blue_dark" to 0xFF0099CC.toInt(),
    "color.holo_green_light" to 0xFF99CC00.toInt(),
    "color.holo_green_dark" to 0xFF669900.toInt(),
    "color.holo_red_light" to 0xFFFF4444.toInt(),
    "color.holo_red_dark" to 0xFFCC0000.toInt(),
    "color.holo_orange_light" to 0xFFFFBB33.toInt(),
    "color.holo_orange_dark" to 0xFFFF8800.toInt(),
    "color.holo_purple" to 0xFFAA66CC.toInt(),
    "color.background_dark" to 0xFF000000.toInt(),
    "color.background_light" to 0xFFFFFFFF.toInt(),
    "color.black" to 0xFF000000.toInt(),
    "color.darker_gray" to 0xFFAAAAAA.toInt(),
)

/**
 * REM-133 fast-follow: the `system_*_disabled` tokens have **no public AOSP `R.color` constant** (they
 * are theme-derived). **Documented §5 approximation** (PO-approved option b): the enabled tone at the
 * Material disabled alpha (38% = [DISABLED_ALPHA]), derived off the *resolved* base so it tracks whatever
 * palette is in effect (baseline for captures, live on Android-app). Refine if test-3's data-oracle later
 * surfaces a canonical value. Maps disabled-name → the base tone name it dims.
 */
internal const val DISABLED_ALPHA: Int = 0x61

internal val DISABLED_TOKEN_BASES: Map<String, String> = mapOf(
    "color.system_on_surface_disabled" to "color.system_on_surface_light",
    "color.system_outline_disabled" to "color.system_outline_light",
    "color.system_surface_disabled" to "color.system_surface_light",
)

/**
 * Merge [base] (the resolved `color.system_*` palette) with the [ANDROID_LEGACY_ALIASES] resolved
 * against it, the [ANDROID_LEGACY_FIXED_COLORS] (REM-133), and the derived [DISABLED_TOKEN_BASES]
 * (REM-133 fast-follow). Shared by the iOS actual, the Android pre-31 fallback, and (via the resolved
 * palette) Android post-31 so all targets surface the same names.
 */
internal fun withLegacyAliases(base: Map<String, Int>): Map<String, Int> {
    val out = LinkedHashMap<String, Int>(
        base.size + ANDROID_LEGACY_ALIASES.size + ANDROID_LEGACY_FIXED_COLORS.size + DISABLED_TOKEN_BASES.size,
    )
    out.putAll(base)
    for ((legacy, systemName) in ANDROID_LEGACY_ALIASES) base[systemName]?.let { out[legacy] = it }
    out.putAll(ANDROID_LEGACY_FIXED_COLORS)
    // Derived §5-approximation: enabled tone's RGB at the Material disabled alpha (38%).
    for ((disabled, baseName) in DISABLED_TOKEN_BASES) base[baseName]?.let {
        out[disabled] = (it and 0x00FFFFFF) or (DISABLED_ALPHA shl 24)
    }
    return out
}
